power_supply: charger-manager: Adjust to new API
Port the driver to new power supply API introduced in v4.1.
Fixes errors:
drivers/power/charger-manager.c: In function ‘update_battery_state’:
drivers/power/charger-manager.c:547:37: warning: initialization from incompatible pointer type [enabled by default]
  struct power_supply *charger_psy = &cm->charger_psy;
                                     ^
drivers/power/charger-manager.c:553:19: error: ‘struct power_supply’ has no member named ‘get_property’
  ret = charger_psy->get_property(charger_psy,

drivers/power/charger-manager.c: In function ‘show_polling_ms’:
drivers/power/charger-manager.c:1125:22: error: request for member ‘dev’ in something not a structure or union
   if (cm->charger_psy.dev == dev)
                      ^
drivers/power/charger-manager.c: In function ‘charger_manager_register_sysfs’:
drivers/power/charger-manager.c:1199:42: error: request for member ‘dev’ in something not a structure or union
  ret = device_create_file(cm->charger_psy.dev, &dev_attr_polling_ms);

Signed-off-by: Krzysztof Kozlowski <k.kozlowski@samsung.com>