ASoC: ymu831: remove IRQF_DISABLED
After mainline commit "d8bf368 genirq: Remove the deprecated
'IRQF_DISABLED' request_irq() flag entirely", IRQF_DISABLED is
removed. The flags is deprecated in early kernel, so it can
be replaced with 0x0 like other drivers.

This patch fixes following build error:
   sound/soc/codecs/ymu831/ymu831.c: In function 'init_irq':
   sound/soc/codecs/ymu831/ymu831.c:8525:54: error: 'IRQF_DISABLED' undeclared (first use in this    function)
     err = request_irq(mc_asoc->pdata->irq, irq_handler, IRQF_DISABLED,
                                                         ^

Change-Id: Id06d964fbe2a62f8c9c642d13479782b9663e7cc
Signed-off-by: Seung-Woo Kim <sw0312.kim@samsung.com>